// See the file "LICENSE" for the full license governing this code.

#include <stdexcept>
#include <string_view>

#include "pybind11/pybind11.h"

namespace swigbind11 {

// clang-format off
struct SwigPyObject {
  PyObject_HEAD
  void* ptr = nullptr;  // raw pointer to the actual C/C++ object
  void* ty = nullptr;
  int own = 0;
  PyObject* next = nullptr;
  PyObject* dict = nullptr;  // optional
};
// clang-format on

namespace py = pybind11;

template <typename T>
auto swig_py_cast(const py::object& obj, std::string_view python_type_name) {
  if (python_type_name.find_last_of('.') == std::string_view::npos) {
    throw std::runtime_error{"python type must be fully qualified, i.e., <module>.<class>"};
  }

  const auto module_name = std::string{python_type_name.begin(), python_type_name.find_last_of('.')};
  python_type_name.remove_prefix(python_type_name.find_last_of('.') + 1);
  const auto python_type = py::module_::import(module_name.c_str()).attr(python_type_name.begin());
  if (!obj.get_type().is(python_type)) {
    throw py::cast_error{"got an unexpected type: " + py::str(py::type::of(obj)).cast<std::string>() + " instead of " +
                         py::str(python_type).cast<std::string>()};
  }

  // obj is a proxy object generated by SWIG, we need to extract the underlying SWIG object
  auto swig_obj = obj.attr("this");
  const auto type = py::str(py::type::of(swig_obj)).cast<std::string>();
  if (type != "<class 'SwigPyObject'>") {
    throw py::cast_error{"expected SWIG-wrapped object, got: " + type};
  }

  // NOLINTNEXTLINE(cppcoreguidelines-pro-type-reinterpret-cast)
  auto* swig_pyobject = reinterpret_cast<SwigPyObject*>(swig_obj.ptr());
  // NOLINTNEXTLINE(cppcoreguidelines-pro-type-reinterpret-cast)
  return reinterpret_cast<T*>(swig_pyobject->ptr);
}

}  // namespace swigbind11